POST http://localhost:3001/api/persons
content-type: application/json

{
	"name": "a",
	"number": "044-1444"
}
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/686673ebc1bc2428882e5bc
###
DELETE http://localhost:3001/api/persons/686671c220ded2e988bae0ae
###
PUT http://localhost:3001/api/persons/68666c4f8028da16bc3cde1
content-type: application/json

{
	"name": "",
	"number": "011-0222"
}
###
DELETE https://phonebook-fullstack-4uwa.onrender.com/api/persons/67240534